# Generated by Django 4.2.28 on 2026-03-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
