# Generated by Django 4.2.28 on 2026-03-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbuapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
