# Generated by Django 4.2.28 on 2026-03-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbuapp', '0003_customuser_address_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
