# Generated by Django 4.2.28 on 2026-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbuapp', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField()),
                ('no_of_dependents', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('self_employed', models.CharField(max_length=10)),
                ('income_annum', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_term', models.FloatField()),
                ('cibil_score', models.FloatField()),
                ('residential_assets_value', models.FloatField()),
                ('commercial_assets_value', models.FloatField()),
                ('luxury_assets_value', models.FloatField()),
                ('bank_asset_value', models.FloatField()),
            ],
        ),
    ]
