# Generated by Django 4.2.28 on 2026-03-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbuapp', '0005_loanprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprediction',
            name='loan_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
