# Generated by Django 4.2.28 on 2026-08-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbuapp', '0006_loanprediction_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprediction',
            name='bank_asset_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loanprediction',
            name='commercial_assets_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loanprediction',
            name='luxury_assets_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loanprediction',
            name='residential_assets_value',
            field=models.FloatField(default=0),
        ),
    ]
